export const sportsProps: { [key: string]: { label: string }[] } = {
  NBA_PROPS: [
    { label: "All" },
    { label: "Pts" },
    { label: "Reb" },
    { label: "Ast" },
    { label: "3pts" },
    { label: "Stl" },
    { label: "Blk" },
    { label: "Pts + Ast" },
    { label: "Pts + Reb" },
    { label: "Reb + Ast" },
    { label: "Pts + Ast + Reb" },
  ],
  MLB_PROPS: [
    { label: "All" },
    { label: "Hr" },
    { label: "H" },
    { label: "R" },
    { label: "RBI" },
    { label: "K" },
    { label: "2B" },
    { label: "3B" },
    { label: "TB" },
    { label: "1B" },
    { label: "SB" },
    { label: "ER" },
  ],
  NBA_MATCHUPS: [
    { label: "Spread" },
    { label: "Totals" },
    { label: "Moneyline" },
    { label: "All" },
  ],
};
